### ISSUE TITLE
Can this package be used in browser?

### ISSUE THREAD

**Issue by uqix** [benbotto/node-data-mapper#4]
If so, our project can use ```DataMapper``` to parse existing query result set.

**Comment by benbotto** [comment]
Hi @uqix,

No, it's meant to run in Node.js and not in the browser.  But that being said, if it's just the `DataMapper` part that you're trying to use then there are very few dependencies.  The `DataMapper` class only depends on the `Schema` class, and that depends on the `assert` function for error handling.  You could pull out those three pieces of the code and use them in browser.

[b]

**Comment by uqix** [comment]
I did what exactly as you say yesterday, and it works, thanks a lot.
